### ISSUE TITLE
Deploy to Sharepoint Online

### ISSUE THREAD

**Issue by leam77** [akorchev/radzen#29]
Is it possible to deploy my Radzen app into Sharepoint Online? I have been exploring the SharePoint Framework and looks promising.

**Comment by akorchev** [comment]
Sorry for the late response. It probably is possible but we have to test it. Will post updates.

**Comment by leam77** [comment]
Thanks!

**Comment by akorchev** [comment]
@leam77 I've managed to upload a Radzen app built for production to a sharepoint online library but couldn't find a way to get a URL to it. Sharepoint always serves the index.html file as an attachment and my browser downloads it instead of displaying it. If there is a way to fix that the app should work.
