### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by codernz** [akorchev/radzen#72]
Is it possible to set a date format in Applications Setting for the whole project

**Comment by akorchev** [comment]
This could be done by setting the default culture.

1. Add at least two cultures - the target one and one more e.g. English - United States.
2. Set the default culture.
3. Rebuild the application.

<img width="523" alt="screen shot 2018-01-10 at 19 05 01" src="https://user-images.githubusercontent.com/454726/34785230-2effbce2-f639-11e7-82a6-962ba6929140.png">

This cause all dates to be formatted according to the default culture.

**Comment by codernz** [comment]
Hi Atanas
I tried that when last year
Have done it again
Set the Cultures both date formats dd/MM/yyyy
[cid:image002.png@01D38B93.48561210]
And still get US format
[cid:image004.png@01D38B93.48561210]

Thanks
Al

**Comment by akorchev** [comment]
What dates do not change? How you display them? My test was done by displaying dates in a DataGrid column that had a template `${data.DateProperty | utcDate}`.

**Comment by codernz** [comment]
Hi
It is a add dialog
[cid:image001.png@01D38C43.DD055CD0]

**Comment by akorchev** [comment]
Good catch! Indeed the calendar component we use doesn't pick up the current culture date format automatically. We will look for possible solutions.

**Comment by codernz** [comment]
Thanks

Sent from Blue<http://www.bluemail.me/r?b=11745>
On 13 Jan 2018, at 10:23, Atanas Korchev <notifications@github.com<mailto:notifications@github.com>> wrote:

Good catch! Indeed the calendar component we use doesn't pick up the current culture date format automatically. We will look for possible solutions.

**Comment by codernz** [comment]
There is a DateFormat  in the calendar component what is the format for this

**Comment by akorchev** [comment]
The DateFormat accepts all format parameters supported by the PrimeNG calendar which Radzen uses:

- d - day of month (no leading zero)
- dd - day of month (two digit)
- o - day of the year (no leading zeros)
- oo - day of the year (three digit)
- D - day name short
- DD - day name long
- m - month of year (no leading zero)
- mm - month of year (two digit)
- M - month name short
- MM - month name long
- y - year (two digit)
- yy - year (four digit)
- @ - Unix timestamp (ms since 01/01/1970)
- ! - Windows ticks (100ns since 01/01/0001)
- '...' - literal text
- '' - single quote
- anything else - literal text

For example `dd.mm.yy`
